disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - statement_position
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Library
variable_name:
  excluded:
    - id
